Url filters
betagouv/itou-marche-api pull request #16
Opened 2021-07-20 14:20 UTC by PieterjanMontens

Quelques améliorations et refactorings techniques, implémentation de retours utilisateur (filtres, date de mise à jour, recherche par siret)

## Changelog :  [0.5] - (2021-07)
- Écriture des vues simplifiée (ModelViewSet et Mixins)
- Filtres sur certains champs (Filterset)
- Wording et endpoint
- Documentation revue
- Accès SIAE par identifiant et siret
- Ajout pagination sur liste SIAE
- Ajout date de mise à jour liste SIAE
- Nouvelle page d'accueil

## A valider / RFC: 
- Utilisation des filtres
- Les vues restent trop grosses, suite à l'usage des token utilisateur et de la sélection du serializer (mode anon ou mode token) en fonction du token
- Le docker compose est dans une autre branche ;)

2021-07-21 09:30 UTC, celine-m-s requested changes
Bravo, gros boulot ! L'interface est super et c'est vraiment bien de voir les dernières nouveautés. Très bonne idée !

Je ne suis pas experte en API, alors j'ai peut-être loupé quelques trucs, mais je t'ai laissé quelques commentaires (notamment un sur `get_object_or_404` qui pourrait te faciliter la vie).

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +            return Directory.objects.get(pk=pk)
Tu peux utiliser la méthode [`get_object_or_404`](https://docs.djangoproject.com/en/3.2/topics/http/shortcuts/#get-object-or-404) de Django. [Lire un exemple tiré de notre code.](https://github.com/betagouv/itou/blob/master/itou/approvals/admin_views.py#L43)

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +            raise Http404
Idem ici. ;-)

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +    queryset = Directory.objects.all()
Je suppose d'ailleurs que c'est le cas car tu utilises `self.get_queryset`.

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +            queryset = self.filter_queryset(self.get_queryset())
Il est peut-être possible de raccourcir un peu le code ainsi : 

```suggestion
            token = request.GET.get("token", None)
            queryset = self.filter_queryset(self.get_queryset())
            if not token:
                queryset = queryset[:10]
```

A tester. :)

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +        queryset = self.get_object_by_id(pk=pk)
Avec le `get_object_or_404`, tu n'auras plus besoin de `get_object_by_id` ! Et hop ! Du code en moins ! ;-)

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +            )
Le `serializer` est exactement le même que l'utilisateur soit authentifié ou pas. Ca vaudrait le coup de factoriser un peu, non ?

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +            except User.DoesNotExist:
:thinking: 
Je me demande si l'erreur renvoyée est `DoesNotExist` si `user.has_perm("api.access_api")` renvoie faux.
A mon avis, ça vaut le coup de faire une méthode à partir de ces quelques lignes (qui se répètent d'ailleurs un peu partout) et de la tester.

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/templates/frontend/home/home.html
> +                    Si vous désirez obtenir un token utilisateur, merci de nous addresser votre demande sur
```suggestion
                    Si vous désirez obtenir un jeton utilisateur, merci de nous adresser votre demande sur
```

:pray: :fr: 
On va encore dire que je suis à cheval sur les mots mais j'assume.

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/templates/frontend/home/home.html
> +                <p>Cet API est encore en construction, et est appellée à évoluer.</p>
```suggestion
                <p>Cette API est encore en construction, et est appelée à évoluer.</p>
```

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/templates/frontend/home/home.html
> +                    <a href="mailt:lemarche@inclusion.beta.gouv.fr" class="text-dark">lemarche@inclusion.beta.gouv.fr</a>
```suggestion
                    <a href="mailto:lemarche@inclusion.beta.gouv.fr" class="text-dark">lemarche@inclusion.beta.gouv.fr</a>
```

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/templates/frontend/home/home.html
> +                            <dd class="col-sm-9">Ajout information (booléén) zone quartier prioritaire de la politique de ville</dd>
```suggestion
                            <dd class="col-sm-9">Ajout information (booléen) zone quartier prioritaire de la politique de la ville</dd>
```

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/templates/frontend/home/home.html
> +                    <p>Interface OpenAPI, aussi connu sous le nom de Swagger</p>
```suggestion
                    <p>Interface OpenAPI, aussi connue sous le nom de Swagger</p>
```

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/templates/frontend/home/home.html
> +                    -->
Ce sera pour plus tard, c'est ça ?

2021-07-21 09:30 UTC, celine-m-s commented on lemarche/templates/layouts/base.html
> +    {%block content%}{%endblock%}
Allez, je pinaille !

```suggestion
    {% block content %}{% endblock %}
```

2021-07-22 08:56 UTC, PieterjanMontens commented on lemarche/api/siaes/views.py
> +    queryset = Directory.objects.all()
Est-ce que `.all()` n'est pas lazy, justement ?
C'est ce que je vois en lisant la doc : `all()` n'est pas repris comme provoquant l'évaluation, et c'est ce que semble confirmer cette réponse sur stack : https://stackoverflow.com/a/42693541

C'est aussi l'exemple utilisé par la doc de ModelViewSet : https://www.django-rest-framework.org/api-guide/viewsets/#modelviewset

J'ai d'abord essayé comme ceci : 
```
    queryset = Directory.objects.none()
    serializer_class = SiaeListSerializer
    filter_class = SiaeFilter

    def get_queryset(self):
        return Directory.objects.all()
```
mais il n'y a aucune différence observable avec l'écriture précédente

2021-07-22 09:00 UTC, PieterjanMontens commented on lemarche/api/siaes/views.py
> +            return Directory.objects.get(pk=pk)
Oh oui, c'est nettement mieux, je peux même supprimer les deux methodes get_by_[id,siret] !

2021-07-22 09:03 UTC, PieterjanMontens commented on lemarche/templates/frontend/home/home.html
> +                    <a href="mailt:lemarche@inclusion.beta.gouv.fr" class="text-dark">lemarche@inclusion.beta.gouv.fr</a>
oh l'horreur..

2021-07-22 09:04 UTC, PieterjanMontens commented on lemarche/templates/frontend/home/home.html
> +                    -->
Je le mets de côté oui ;)

2021-07-22 09:07 UTC, PieterjanMontens commented on lemarche/api/siaes/views.py
> +        queryset = self.get_object_by_id(pk=pk)
C'est tout juste !

2021-07-22 09:07 UTC, PieterjanMontens commented on lemarche/api/siaes/views.py
> +    queryset = Directory.objects.all()
En plus avec l'utilisation de get_object_or_404, c'est encore plus simple :D

2021-07-22 09:32 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +    queryset = Directory.objects.all()
Oooh ! J'ai appris une subtilité et j'en suis bien contente !
Quand la `queryset` est assignée à une variable, elle n'est pas évaluée (même avec un `.all`). Elle ne l'est que [dans ces cas](https://docs.djangoproject.com/en/3.2/ref/models/querysets/#when-querysets-are-evaluated) : 
- itération
- segmentation
- pickling
- `repr()`
- `len`
- `list()`
- Condition (booléen)

Merci, ça m'a permis de relire la doc !

2021-07-22 13:19 UTC, PieterjanMontens commented on lemarche/api/siaes/views.py
> +            except User.DoesNotExist:
Ah clairement pas ! c'est `AssertionError` la bonne exception.

J'ai fait une méthode unique, qui fonctionne un peu comme get_object_or_404 et qui soulève une exception (http 401) en cas de manque de permissions, merci pour l'idée :+1:

2021-07-22 14:22 UTC, celine-m-s commented on lemarche/api/siaes/views.py
>  # TODO: create common shared lib for reusable components
En voilà une riche idée ! Exactement ce que je me disais en lisant cette portion de code ! :smile:

2021-07-22 14:22 UTC, celine-m-s commented on lemarche/api/siaes/views.py
> +        raise Unauthorized
:+1: 
Super !

2021-07-22 14:25 UTC, celine-m-s approved these changes
LGTM
Merci pour les changements !

2021-07-23 12:47 UTC, merged