Test static page
betagouv/itou-marche-api pull request #17
Opened 2021-07-30 12:41 UTC by PieterjanMontens

Intégration d'une page statique qui : 
- est une migration de itou-cocorico
- utilise les composants de base ( base / layout / header / footer) eux-aussi migrés depuis itou-cocorico
- utilise le theme itou
- permet l'utilisation de sass/scss (compressé)

Aperçu de la page (Original sur https://lemarche.inclusion.beta.gouv.fr/fr/itou/inclusion ) : 
![Screenshot 2021-07-30 at 14-39-53 - marché de l'inclusion](https://user-images.githubusercontent.com/4528178/127654344-466bde2c-16e8-48ba-a306-86b837a0a5e9.png)

2021-07-30 13:14 UTC, Keirua approved these changes
Ca me parait bien (bien joué pour la migration casse figure, mais c’est vrai que Twig est très inspiré de Jinja).
Pour info, si on commence à migrer des pages statiques ici, j’imagine qu’à terme, ce projet n’aura donc pas juste qu’une API, mais aussi un front ?

2021-08-04 10:11 UTC, celine-m-s requested changes
Quelques petites fautes de frappe mineures par-ci, par-là.
Je me demande pourquoi tu as utilisé `django-environ` au lieu du classique `os.environ`. :)

2021-08-04 10:11 UTC, celine-m-s commented on lemarche/templates/frontend/pages/inclusion.html
> +                        <p>Aujourd'hui, des entreprises ont déjà  franchis le pas de travailler avec le secteur inclusif . Des exemples de  belles collaborations</p>
```suggestion
                        <p>Aujourd'hui, des entreprises ont déjà franchi le pas de travailler avec le secteur inclusif. Des exemples de belles collaborations.</p>
```

2021-08-04 10:11 UTC, celine-m-s commented on lemarche/templates/frontend/pages/inclusion.html
> +                      <p>Soutien de l’emploi en situation de handicap  tout en réduisant vos contributions Agefiph/Fiphfp</p>
```suggestion
                      <p>Soutien de l’emploi en situation de handicap tout en réduisant vos contributions Agefiph/Fiphfp</p>
```

2021-08-04 10:11 UTC, celine-m-s commented on lemarche/templates/layouts/base-itou.html
> +  <noscript>Javascript must be enabled for the correct page display</noscript>
Cela vaut peut-être la peine de traduire ce message en français ?

2021-08-04 10:11 UTC, celine-m-s commented on lemarche/templates/layouts/base-itou.html
> +      <a tabindex="1" href="#main">skip to content</a>
Idem :fr:

2021-08-04 10:11 UTC, celine-m-s commented on lemarche/templates/layouts/base-itou.html
> +      <a href="#header">back to top</a>
Idem :fr:

2021-08-04 10:12 UTC, celine-m-s commented
Au fait, c'est TOP d'avoir ce nouveau thème et que les `assets` soient compressés automatiquement ! Beau boulot ! :clap: :champagne:

2021-09-01 07:57 UTC, PieterjanMontens commented on config/settings/base.py
> +env = environ.Env(DEBUG=(bool, False))
Yes, j'avais vite mis le lien vers la doc, mais de fait ça mérite un peu plus d'explications.

En gros django-environ facilite l'application de la méthode 12-factor : moins de code pour faire la même chose, et je trouve plus clair, ça évite les erreurs, et le tout est plus compréhensible à la lecture grâce au typage : 

```
DEBUG = env.bool('DEBUG', False)
vs
DEBUG = os.environ.get("DEBUG") == "True" # .get returns None, aka False, if the value if not found.
```
Sans parler de quelques helpers bien pratiques (comme pour le path)

La doc : https://django-environ.readthedocs.io/en/latest/

2021-09-01 07:59 UTC, PieterjanMontens commented on lemarche/templates/layouts/base-itou.html
> +  <noscript>Javascript must be enabled for the correct page display</noscript>
tout à fait :+1:

2021-09-01 09:04 UTC, PieterjanMontens commented on config/settings/base.py
> +#STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
pour pouvoir faire de l'élagage par après ! :D :scissors:

2021-09-01 09:04 UTC, PieterjanMontens commented on config/settings/base.py
> +#STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
(je supprime celle-ci)

2021-09-01 09:05 UTC, PieterjanMontens commented on config/settings/base.py
> +# COMPRESS_CACHEABLE_PRECOMPILERS = (("text/x-scss", "django_libsass.SassCompiler"),)
:fallen_leaf:

2021-09-01 09:05 UTC, PieterjanMontens commented on config/settings/base.py
> +# COMPRESS_CACHEABLE_PRECOMPILERS = (("text/x-scss", "django_libsass.SassCompiler"),)
(c'est bientôt l'automne)

2021-09-01 09:05 UTC, PieterjanMontens commented on config/settings/base.py
> +        "PORT": env.str("MYSQL_ADDON_PORT"),
Trooooo forte ! :muscle:

2021-09-01 09:09 UTC, raphodn commented on config/settings/base.py
> +env = environ.Env(DEBUG=(bool, False))
Ca éviterait aussi d'avoir un script pour initialiser les env il me semble ?
En tout cas je trouve que ca clarifie un peu le fichier de settings.
Après je suis ouvert à l'idée de l'enlever plus tard :stuck_out_tongue:  si c'est trop magique

2021-09-01 09:10 UTC, raphodn commented on config/settings/base.py
> +        "PORT": env.str("MYSQL_ADDON_PORT"),
ca serait possible avec https://pypi.org/project/dj-database-url/ je crois

2021-09-01 09:11 UTC, PieterjanMontens commented on config/settings/base.py
> +        "PORT": env.str("MYSQL_ADDON_PORT"),
Je le note pour après, ça demande d'être testé ça ;)

2021-09-01 09:18 UTC, PieterjanMontens commented on config/settings/base.py
> +env = environ.Env(DEBUG=(bool, False))
C'est de la transmutation de variables antiques en données typées par inférence et polymorphisme abstrait et paramétré ! :alembic:

2021-09-01 09:21 UTC, PieterjanMontens commented on docs/twig_vers_django.md
> +- les commentaires twig style `{# HELLO WORLD ! #}` ne fonctionnent pas sous django
Ah ouais ? Trop cool, je ne le trouvais nulle part dans la doc. Merci ! (je testerai quand même avant :shushing_face: )

2021-09-01 09:22 UTC, PieterjanMontens commented on lemarche/templates/frontend/common/_itou_footer.html
> +            <img src="{% static 'itou/images/logo-republique-francaise.svg' %}" alt="Rébublique Française" class="img-fluid">
Brésident de la Rebublique ! :100:

2021-09-01 09:24 UTC, PieterjanMontens commented on lemarche/templates/frontend/common/_itou_footer.html
> +          <li><a href="https://github.com/betagouv/itou-cocorico/" rel="noopener" target="_blank" class="is-external">{{ 'Github' }}</a></li>
Ça fait une chaîne de caractère en fait.. c'est complètement inutile :innocent:

2021-09-02 08:00 UTC, merged